"use client";
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '../components/Navbar';
import { Urbanist, Tangerine, Josefin_Slab } from 'next/font/google';
import { Provider } from 'react-redux';
import { store } from '@/store/store';
import Footer from '@/components/Footer';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const tangerine = Tangerine({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-tangerine',
});

const slab = Josefin_Slab({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-slab',
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Teekay Stores | The Essence Of Elegance</title>

      {/* <!-- Meta Tags for SEO --> */}
      <meta name="description" content="Teekay stores was born from a passion for refined craftsmanship and a deep appreciation for the art of femininity, we create bags that exude sophistication. Each piece is thoughtfully designed to bring out the unique beauty of every woman, merging classic elegance with modern flair." />
      <meta property="og:title" content="Teekay Stores | The Essence Of Elegance" />
      <meta property="og:description" content="Discover a world where femininity meets elegance, crafted in every stitch, every silhouette. Our bags blend timeless glamour with modern allure, designed to be the perfect companion for every moment." />
      <meta property="og:image" content="/favicon.ico" />
      <link rel="icon" href="/favicon.ico" className=' rounded-full'/>
      <meta property="og:url" content="https://teekaybags.store/" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#fffaf6] overflow-x-clip scroll-smooth`}
      >
        <main
          className={`${slab.className} ${tangerine.variable} ${slab.variable}`}
        >
          <Provider store={store}>
            <Navbar />
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
            {children}
            {/* <Footer /> */}
          </Provider>
        </main>
      </body>
    </html>
  );
}
